version: '3.4'

services:
  mssql-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "1Secure*Password1"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql/data
      - ./Database:/usr/work
    command: /bin/bash -c "while ! /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P '1Secure*Password1' -Q 'SELECT 1;' ; do sleep 1 ; done"
  
  swapy-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mssql-db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONNECTION_STRING: "Server=mssql-db;Database=Swapy;User Id=sa;Password=1Secure*Password1"
  
volumes:
  dbdata: